### ISSUE TITLE
lighthouse domhtml is going away

### ISSUE THREAD

**Issue by paulirish** [dschmeh/lighthouseR#1]
heya! cool project! :)  

btw i have a PR that will change the default output from `domhtml` to `html`. https://github.com/GoogleChrome/lighthouse/pull/4176

 looks like this package will require a small change. might as well tweak these regexes to handle both cases:
https://github.com/dschmeh/lighthouseR/blob/ea7cea4325e7bb0436348836b9bc7c010912d8a9/R/lighthouse.R#L40-L42

cheers!

**Comment by dschmeh** [comment]
@paulirish Thank you! I changed the function so it can process both.
